### ISSUE TITLE
[Study] Telegraf, Kafka의 모든것

### ISSUE THREAD

**Issue by Moon-janggon** [nhnacademy-aiot2-javame/javame-templates#42]
# 📚 공부 기록 - Telegraf,Kafka 개념 및 로컬/서버 설정법

- 📅 날짜: 2025-04-17
- ✍️ 작성자: 문장곤

---

## ✨ 오늘의 내용 요약
Telegraf -> 데이터 수집기
- 많은 프로토콜 및 시스템 리소스를 수집하는 용도 

Kafka -> 수집한 데이터를 서비스에 전달하기 위해 사용하는 mqtt와 유사하지만 더 강력한 대용량 처리기

---

## 📖 상세 내용
{{공부한 내용을 자세히 정리합니다. 코드, 설명, 느낀 점 등 포함}}

# Telegraf 
Telegraf는 데이터베이스, 시스템 및 IoT 센서에서 메트릭 및 이벤트를 수집하고 전송하기 위한 플러그인 중심 서버 에이전트입니다. Telegraf는 Go로 작성되었으며 외부 종속성 없이 단일 바이너리로 컴파일되며 최소한의 메모리 공간만 필요합니다.

🔵 모든 종류의 데이터 수집 및 전송

- 데이터베이스

MongoDB, MySQL, Redis 등의 데이터 소스에 연결하여 메트릭을 수집하고 보냅니다.

- 시스템

현대적인 클라우드 플랫폼, 컨테이너 및 오케스트레이터 스택에서 메트릭을 수집합니다.

- IoT 센서

IoT 센서 및 장치에서 중요한 상태 저장 데이터(압력 수준, 온도 수준 등)를 수집합니다.

# Kafka 
카프카(Kafka)는 파이프라인, 스트리밍 분석, 데이터 통합 및 미션 크리티컬 애플리케이션을 위해 설계된 고성능 분산 이벤트 스트리밍 플랫폼이다.

Pub-Sub 모델의 메시지 큐 형태로 동작하며 분산환경에 특화되어 있다.

## ❓Kafka를 쓰는 이유
JavaMe-Iot 서버 운영 프로젝트에서 수집되는 데이터는 크게 서버 리소스/ Iot센서로 부터 받는 mqtt/modbus로 크게 3가지가 있고 특히 서버 리소스는 약 1~2초당 한번씩 송신되는 데이터로 
처리해야할 용량이 많기 때문에 기존 프로젝트에서 써왔던 mqtt보다 서버 운영에 적합한 분산 스트리밍 플랫폼.

```
//docker-compose.yml 내 서비스 등록 방식

kafka:
    image: bitnami/kafka:latest
    container_name: javame-kafka
    ports:
      - "10289:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093 
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:10289,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - default
    restart: unless-stopped
```
프로젝트 내 적용 구조

-docker에서 kafka를 사용하기위해 설정하는 형식으로
docker-compose 관련 정보 
#{링크-도커 컴포즈 스터디 링크 필요}

kafka를 로컬에서 테스트 하려면 로컬에 kafka를 설치해야함 (원격 서버는 현재 권한 부족으로 포트 개방 불가)
따라서  JavaMe 프로젝트에서는 테스트를 위해 spring boot service를 jar로 패키징해 원격서버에서 docker 이미지로 사용하여
서버내에서 log로 테스트하는 방식을 선택함

연결구조 telegraf-> kafka -> 필요한 서비스 구조로 되어있으며
docker-compose로 docker이미지를 관리하여 내부 연결망으로 통신

## telegraf 사용법
1.telgraf 설치 (현재 서버는 docker-container 에 설치 되어있음 로컬에서 설치하려면 pip install등 활용)
2.docker-compose.yml 설정 (로컬 제외)
3.telegraf.conf 

```
[agent]
  interval = "5s"
  round_interval = true
  omit_hostname = false

[[outputs.kafka]]
  brokers = ["kafka:9092"]
  topic = "telegraf.metrics"
  data_format = "influx"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = true

[[inputs.mem]]
[[inputs.disk]]
[[inputs.system]]
```
중요점 -> 
Kafka->   - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093 
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:10289,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      kafka가 청취할 포트 요청 -> 이것 때문에 내부 외부가 방화벽으로 막혀있으면 로컬에서 테스트 불가(현재 원격서버 상태)

## 📎 참고 파일  

---

## 💡 느낀 점 / 다음 목표
권한 없으면 참 힘들다
---
