### ISSUE TITLE
[Study] Docker와 Docker-compose

### ISSUE THREAD

**Issue by InSeong23** [nhnacademy-aiot2-javame/javame-templates#58]
# 📚 공부 기록 - {{Docker와 Docker-compose}}

- 📅 날짜: {{2025-04-24}}
- ✍️ 작성자: {{임성인}}

---

## ✨ 오늘의 내용 요약
{{Docker는 애플리케이션과 그 환경을 컨테이너로 묶어서 배포할 수 있는 플랫폼이며,
Docker-Compose는 여러 컨테이너를 정의하고 관리할 수 있는 도구이다.}}

---

### Docker란?

- 컨테이너 기반 가상화 기술로, 애플리케이션과 그 종속성을 패키징해 어디서든 실행 가능하게 함.
- VM보다 가볍고 빠름.
- Dockerfile을 통해 이미지 생성 → 컨테이너로 실행.

---
### Dockerfile이란?
-Docker 이미지를 만들기 위한 설정 파일

---

```bash
# Dockerfile 예시
FROM python:3.9-slim
#베이스 이미지 설정
WORKDIR /app
#작업 디렉토리 설정: 이후의 명령어가 /app 경로에서 실행
COPY . .
#로컬의 모든 파일을 컨테이너로 복사:  현재 폴더(.)에 있는 파일들을 컨테이너의 /app에 삽입
RUN pip install -r requirements.txt
#패키지 설치 명령어 실행: 파이썬 패키지 목록이 적힌 requirements.txt를 읽어 필요한 라이브러리를 설치
CMD ["python", "batch_runner.py"] 
#컨테이너 실행 시 수행할 명령 
```
### Docker Compose란?

- 여러 개의 Docker 컨테이너를 한 파일(yml)로 정의하고 관리할 수 있는 도구.
- docker-compose.yml 파일 하나로 웹서버, DB, 캐시 등 연동 가능.

```yaml

version: "3.8"

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: javame-kafka
    ports:
      - "10289:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:10289,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - default
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7.11
    container_name: javame-influxdb
    ports:
      - "10288:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=javamelive1234
      - DOCKER_INFLUXDB_INIT_ORG=javame
      - DOCKER_INFLUXDB_INIT_BUCKET=aiot
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=g-W7W0j9AE4coriQfnhHGMDnDhTZGok8bgY1NnZ6Z0EnTOsFY3SWAqDTC5fYlQ9mYnbK_doR074-a4Dgck2AOQ==
    networks:
      # <<< 네트워크 설정 추가 >>>
      - javame-network
    restart: unless-stopped

  telegraf:
    image: telegraf:1.27
    container_name: javame-telegraf
    depends_on: 
      - kafka
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      # <<< 네트워크 설정 수정 >>>
      - javame-network
    restart: unless-stopped

  ai-prediction:
    build: 
      context: ../ai-prediction
      dockerfile: Dockerfile
    container_name: javame-ai-prediction
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=g-W7W0j9AE4coriQfnhHGMDnDhTZGok8bgY1NnZ6Z0EnTOsFY3SWAqDTC5fYlQ9mYnbK_doR074-a4Dgck2AOQ==
      - INFLUXDB_ORG=javame
      - INFLUXDB_BUCKET=aiot
      - PREDICTION_INTERVAL=6
      - MYSQL_HOST=s4.java21.net
      - MYSQL_PORT=13306
      - MYSQL_USER=aiot02_team3
      - MYSQL_PASSWORD=ryL7LcSp@Yiz[bR7
      - MYSQL_DATABASE=aiot02_team3
    volumes:
      - ../ai-prediction:/app
    networks:
      - javame-network
    restart: unless-stopped
    depends_on:
      - influxdb

  rule-engine:
   image: eclipse-temurin:21-jdk-jammy
   container_name: javame-rule-engine
   environment: 
     - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
   volumes:
     - ./rule-engine.jar:/app/app.jar
   working_dir: /app
   command: ["java","-jar","app.jar"]
   ports:
     - "10287:10287"

  mosquitto: # <<< Mosquitto 서비스 정의 추가 >>>
    image: eclipse-mosquitto:latest
    container_name: javame-mosquitto
    ports:
      - "10282:1883" # 사용하기로 한 호스트 포트
      - "10283:9001" # 사용하기로 한 웹소켓 포트
    networks:
      # <<< 네트워크 설정 추가 >>>
      - javame-network
    volumes:
      # docker-compose.yml과 같은 디렉토리의 mosquitto.conf 파일을 마운트 (읽기 전용)
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      # 데이터 저장을 위한 볼륨 마운트
      - mosquitto_data:/mosquitto/data
      # -------------
    restart: unless-stopped



volumes:
  influxdb_data:
  kafka_data:
  mosquitto_data:

networks:
  javame-network:
    external: true

```

---

## 📎 참고 파일  
-- aiot2-team3@ubuntu서버내 ~/docker/docker-compose.yml 
-- aiot2-team3@ubuntu서버내 ~/ai-prediction/Dockerfile 

---
