### ISSUE TITLE
Docker-Compose / 도커 배포의 정석

### ISSUE THREAD

**Issue by Moon-janggon** [nhnacademy-aiot2-javame/javame-templates#64]
# Docker
도커란 무엇인가?

Docker는 애플리케이션을 실행할 때 필요한 모든 파일, 라이브러리, 설정 등을 하나의 컨테이너라는 격리된 환경에 넣어서 실행할 수 있게 해주는 도구입니다. 쉽게 말해, "어디서든 똑같이 실행되는 환경"을 만들어주는 도구입니다.

# Docker-Compose
도커 컴포즈는 무엇인가?

Docker Compose는 여러 개의 Docker 컨테이너를 하나의 설정 파일로 관리하고, 한 번에 실행할 수 있게 해주는 도구입니다. 예를 들어, 웹 서버, 데이터베이스 서버, 캐시 서버 등을 각각 Docker 컨테이너로 만들고, Compose 파일로 이를 하나로 묶어 놓으면, 한 번의 명령으로 모든 서비스를 동시에 시작하거나 종료할 수 있습니다.

결론 : Docker와 Docker-compose를 이용해서 CI/CD를 git actions를 통해 자동화할 예정

# CI/CD
## Step1
Java-Spring 기반 Dockerfile 생성

<img width="321" alt="Image" src="https://github.com/user-attachments/assets/e1b2db5a-8ecd-46bc-8650-cfd9b2ba9801" />

프로젝트 최상단 Dockerfile 생성

```
//Dockerfile
FROM ubuntu:latest
LABEL authors="goni"

ENTRYPOINT ["top", "-b"]

# 1. 공식 OpenJDK 런타임을 기본 이미지로 사용 ( 컨테이너 안에 설치될 jdk를 나타냄)
FROM openjdk:21-jdk-slim

# 2. 컨테이너 내에서 작업 디렉토리 설정
WORKDIR /app

# 3. 빌드된 JAR 파일을 컨테이너로 복사
# 'javame-trans-service.jar'은 예시고 자신의 레포 이름으로 설정하면 됨
COPY target/*.jar javame-trans-service.jar

# 4. Spring Boot 앱이 실행될 포트 노출
EXPOSE 10284

# 5. Spring Boot JAR 파일 실행
CMD ["java", "-jar", "javame-trans-service.jar"]
```

## Step2
Docker_Hub 가입 (git으로 가입 추천)

![Image](https://github.com/user-attachments/assets/36b09ec4-2341-45ca-b805-807ba58d1097)
레포지토리 만들기 (레포지 이름만 기입하면됨 ex( trans-service o , janggon/trans-service x)

![Image](https://github.com/user-attachments/assets/d84951be-2257-4f69-99c3-3ece6f6edc54)
/앞 DOCKER_USERNAME /뒤 레포지토리 이름 ( git-repository랑 통일 추천)

### workflows 구성하기

![Image](https://github.com/user-attachments/assets/b0d902bb-4d45-4a47-8b07-f0c869e01a76)

```
name: CI/CD for Spring Boot with Docker

on:
  push:
    branches:
      - main
 


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: javame-trans-service

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK environment
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build the Spring Boot application
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build & Push Docker Image
        run: |
            IMAGE_TAG=${{ github.sha }}
            docker build -t janggon/javame-trans-service:$IMAGE_TAG .
            docker push janggon/javame-trans-service:$IMAGE_TAG
            echo "TRANS_IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # Deploy the application using Docker-Compose
      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            port: 8822
            key: ${{ secrets.PRIVATE_KEY }}
            script: |
              COMPOSE_DIR="/home/aiot2/aiot2-team3/docker/javame"
              cd $COMPOSE_DIR
              
              # ① .env에 방금 빌드한 이미지 태그 기록
              if grep -q '^TRANS_IMAGE_TAG=' .env; then
               # 있으면 교체
              sed -i "s|^TRANS_IMAGE_TAG=.*|TRANS_IMAGE_TAG=${{ env.TRANS_IMAGE_TAG }}|" .env
              else
              # 없으면 추가
              echo "TRANS_IMAGE_TAG=${{ env.TRANS_IMAGE_TAG }}" >> .env
              fi
              
              SERVICE_NAME=javame-trans-service
              docker-compose stop $SERVICE_NAME
              docker-compose rm -f $SERVICE_NAME
              docker-compose up -d $SERVICE_NAME
             


```

Sercret 키 설정해주기 ( git-secret )
- DOCKER_USERNAME : Docker 유저네임
- DOCKER_PASSWORD : Docker 패스워드 ( 토큰 추천 )
- REMOTE_USER : aiot2-team3
- REMOTE_HOST : s2.java21.net 
- PRIVATE_KEY : 자기 git_rsa 비밀키

## Step4

docker-compose.yml 작성

원격 서버지
(javame-docker-compose경로 /home/aiot2/aiot2-team3/docker/javame)
에 docker-compose.yml 수정

```
  javame-trans-service:
    image: "janggon/javame-trans-service:${TRANS_IMAGE_TAG}"
//여기 주의 workFlow에서 정한 tag이미지 변수로 변경
    container_name: javame-trans-service
    ports:
      - "10284:10284"
    restart: unless-stopped
```

이렇게 설정하고 메인에 푸쉬 후 정상 배포되면

# 끝!
