### ISSUE TITLE
[Study] 서비스 성능 테스트 구현

### ISSUE THREAD

**Issue by jangwonseong** [nhnacademy-aiot2-javame/javame-templates#71]
# 📚 스터디 기록 - OpenTelemetry Java Agent & Collector 연동 (외부망 환경)

- 📅 날짜: 2025-05-08
- ✍️ 작성자: 성장원

---

## 🎯 프로젝트 목표

외부 네트워크 환경에서 실행 중인 Spring Boot 애플리케이션의 성능 및 상태 데이터를 OpenTelemetry Java Agent를 사용하여 수집하고, 이를 내부 네트워크의 OpenTelemetry Collector로 전송한 후, Milesight UG65 게이트웨이의 Node-RED를 통해 데이터를 처리 및 확인하는 전체 파이프라인을 구축합니다.

---

## 🛠️ 적용법 및 설치 가이드

이 가이드는 유사한 환경에서 OpenTelemetry를 설정하려는 분들을 위해 작성되었습니다.

### 1단계: 사전 준비물

- **Spring Boot 애플리케이션:** 모니터링 대상이 될 Java 애플리케이션 (예: `hello.jar`).
- **OpenTelemetry Java Agent:** 최신 버전의 `opentelemetry-javaagent.jar` 파일.
- **OpenTelemetry Collector:** Collector를 실행할 PC 또는 서버 (이 가이드에서는 "게이트웨이 전용 PC"로 지칭).
- **Milesight UG65 LoRaWAN 게이트웨이 (또는 유사 네트워크 장비):** 포트 포워딩(Port Mapping) 기능 및 Node-RED 실행 환경 제공.
- **Node-RED:** UG65 게이트웨이 또는 별도 서버에 설치된 Node-RED.

### 2단계: OpenTelemetry Java Agent 다운로드

Spring Boot 애플리케이션을 실행할 PC(이하 "Spring PC")에서 다음 명령으로 Java Agent를 다운로드합니다.

```bash
wget https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar
````

다운로드된 `opentelemetry-javaagent.jar` 파일은 실행 시 쉽게 접근 가능한 경로에 둡니다 (예: `/home/사용자명/`).

### 3단계: OpenTelemetry Collector 설정 (게이트웨이 전용 PC)

게이트웨이 전용 PC에 OpenTelemetry Collector Contrib 배포판을 설치합니다. (설치 방법은 [[공식 문서](https://opentelemetry.io/docs/collector/getting-started/)](https://opentelemetry.io/docs/collector/getting-started/) 참고)

Collector 설정 파일 (`config.yaml`)을 다음과 같이 작성합니다. (예: `/etc/otelcol-contrib/config.yaml` 또는 사용자가 지정한 경로)

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317" # Java Agent로부터 OTLP/gRPC 데이터 수신
      http:
        endpoint: "0.0.0.0:4318" # OTLP/HTTP 데이터 수신 (선택 사항)

processors:
  batch: # 데이터를 일괄 처리하여 효율성 증대

exporters:
  logging:
    verbosity: detailed # 수신된 데이터를 콘솔에 상세 로깅 (디버깅용)
  
  otlphttp: # Node-RED로 데이터를 OTLP/HTTP 형식으로 내보내기
    endpoint: "https://<Node-RED-주소>/otlp_unified" # Node-RED 엔드포인트 주소
    tls:
      insecure_skip_verify: true # Node-RED가 자체 서명 SSL 인증서 사용 시 검증 건너뛰기
    headers:
      "Content-Type": "application/json" # Node-RED가 JSON 페이로드를 받도록 명시
    compression: "none" # 압축 없이 JSON 텍스트 전송 (Node-RED 처리 용이)

service:
  extensions: [health_check] # Collector 상태 확인 엔드포인트 활성화 (선택 사항)
  pipelines:
    metrics: # 메트릭 데이터 파이프라인
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
    traces: # 트레이스 데이터 파이프라인 (필요시 구성)
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
    logs: # 로그 데이터 파이프라인 (필요시 구성)
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
```

**설정 후 Collector 실행:**

```bash
sudo otelcol-contrib --config /경로/to/your/config.yaml
# 또는 systemd 서비스로 등록하여 실행
```

### 4단계: UG65 게이트웨이 설정 (외부망 접속 허용)

Spring PC가 외부 네트워크에 있고 Collector PC가 UG65 게이트웨이 내부망에 있을 경우, 외부에서 Collector로 접속할 수 있도록 UG65 설정을 변경합니다.

1. **UG65 게이트웨이 공인 IP 주소 확인 또는 DDNS 설정:**

   * 게이트웨이가 인터넷에서 사용하는 공인 IP를 확인합니다.
   * **권장:** UG65 관리자 페이지 "Network" > "DDNS" 메뉴에서 DDNS 서비스를 설정하여 고정된 도메인 이름(예: `my-collector.ddns.net`)을 확보합니다.

2. **포트 포워딩 (Port Mapping) 설정:**

   * UG65 관리자 페이지 "Network" > "Port Mapping" 메뉴로 이동합니다.
   * 새로운 규칙을 추가합니다:

     * **Source IP:** (비워둠 - 모든 외부 IP 허용)
     * **Source Port (외부 포트):** `4317` (Java Agent가 접속할 포트)
     * **Destination IP (내부 IP):** Collector PC의 내부 IP 주소 (예: `192.168.1.108`)
     * **Destination Port (내부 포트):** `4317` (Collector가 리스닝하는 포트)
     * **Protocol:** `TCP`
     * **Description:** `OTel Collector gRPC` (또는 적절한 설명)
     * 규칙을 \*\*활성화(Enable)\*\*하고 저장/적용합니다.

3. **방화벽 확인 (필요시):**

   * "Network" > "Firewall" 메뉴에서 위 "Source Port"에 대한 외부 TCP 연결이 허용되었는지 확인합니다.

### 5단계: Spring Boot 애플리케이션 실행 (Java Agent와 함께)

Spring PC에서 애플리케이션을 다음 명령어로 실행합니다. `-Dotel.exporter.otlp.endpoint` 값을 UG65 게이트웨이의 공인 IP (또는 DDNS 도메인)와 포트 포워딩에서 설정한 외부 포트로 변경해야 합니다.

```bash
java -javaagent:/경로/to/opentelemetry-javaagent.jar \
     -Dotel.service.name=javame-frontend \
     -Dotel.exporter.otlp.endpoint=http://<게이트웨이-공인-IP>:4317 \
     -Dotel.exporter.otlp.protocol=grpc \
     -Dotel.resource.attributes=company_domain=javame,environment=gyeongnam_campus,place=spring_pc,ipHost=<Spring-PC-IP> \
     -jar target/hello.jar
```

* `<게이트웨이-공인-IP>`: 4-1 단계에서 확인/설정한 값으로 대체합니다.
* `<Spring-PC-IP>`: `ipHost` 속성은 참고용이며, 실제 데이터 전송에는 `otlp.endpoint`가 사용됩니다.

### 6단계: Node-RED 플로우 구성 (데이터 수신 및 처리)

UG65 게이트웨이의 Node-RED 편집기에서 다음 플로우를 구성합니다.

1. **HTTP In 노드 (Metrics 수신 예시):**

   * Method: `POST`
   * URL: `/otlp_unified/v1/metrics`

2. **JSON 노드:**

   * Action: "Always convert to JavaScript object" (또는 입력이 이미 객체면 통과하도록 설정)
   * Purpose: `http in` 노드가 `Content-Type: application/json` 헤더를 보고 자동으로 파싱한 JavaScript 객체를 그대로 사용하거나, 문자열일 경우 객체로 변환.

3. **Debug 노드 (파싱된 데이터 확인용):**

   * Output: `msg.payload`
   * To: "debug window"

4. **Function 노드 (필요 정보 추출 및 MQTT 메시지 생성):**

   * `msg.payload` (OTLP/JSON 객체)를 입력받아 원하는 정보(예: 서비스 이름, CPU 사용률, 메모리 사용량, HTTP 요청 수 등)를 추출하고, MQTT로 발행할 토픽과 페이로드 형식으로 가공합니다. (상세 코드는 아래 "📖 상세 내용" 참고)

5. **Split 노드 (선택 사항):**

   * Function 노드가 여러 MQTT 메시지를 배열로 반환했을 경우, 이를 개별 메시지로 분리합니다.

6. **MQTT Out 노드:**

   * 가공된 데이터를 MQTT 브로커로 발행합니다. (Topic, Broker 등 설정 필요)

7. **HTTP Response 노드:**

   * `http in` 노드에 대한 응답을 Collector에게 보냅니다. (예: `msg.statusCode = 200; msg.payload = {"status":"ok"};`) 이 노드가 실행되어야 Collector에서 타임아웃 에러가 발생하지 않습니다.

**플로우 예시:**

`[HTTP In]` → `[JSON]` → `[Debug (Parsed OTLP)]` → `[Function (Extract & Prepare MQTT)]` → (선택적: `[Split]`) → `[MQTT Out]`

별도 경로: `[Debug (Parsed OTLP)]` → `[Function (Set HTTP 200 OK)]` → `[HTTP Response]`

이제 외부 네트워크의 Spring PC에서 발생한 메트릭 데이터가 Collector를 거쳐 Node-RED로 전송되고, MQTT로 발행될 준비가 되었습니다.

---

## 📖 상세 내용 (학습 및 문제 해결 과정)

**핵심 문제 해결 포인트:**

1. **외부망 접속:** Spring PC와 Collector PC 간의 네트워크 분리 문제를 UG65 게이트웨이의 **포트 포워딩(Port Mapping)** 기능을 통해 해결. Collector PC가 연결된 게이트웨이에서 외부 포트와 내부 Collector PC IP/
